- name: Parar o Apache
  systemd:
    name: apache2
    state: stopped
  when: ansible_os_family == "Debian"

- name: Remover o Apache
  Package:
    name: apache2*
    state: absent
  when: ansible_os_family == "Debian"

